# Os jogadores podem ferir e matar outros jogadores
PVP=true

# O tempo do jogo � parado quando n�o h� jogadores online
PauseEmpty=true

# Ativa ou desativa o bate-papo global.
GlobalChat=true

ChatStreams=s,r,a,w,y,sh,f,all

# Os jogadores podem participar sem j� ter uma conta na lista de permiss�es. Se definido como falso, os administradores devem criar manualmente combos de nome de usu�rio/senha.
Open=true

# A primeira mensagem de boas-vindas vis�vel no painel de bate-papo. Isso ser� exibido imediatamente ap�s o login do jogador. Voc� pode usar cores RGB para alterar a cor da mensagem de boas-vindas. Voc� tamb�m pode usar <LINE> para criar linhas separadas em seu texto. Use: <RGB:1,0,0> Esta mensagem aparecer� em vermelho!
ServerWelcomeMessage=Welcome to Project Zomboid Multiplayer! <LINE> <LINE> To interact with the Chat panel: press Tab, T, or Enter. <LINE> <LINE> The Tab key will change the target stream of the message. <LINE> <LINE> Global Streams: /all <LINE> Local Streams: /say, /yell <LINE> Special Steams: /whisper, /safehouse, /faction. <LINE> <LINE> Press the Up arrow to cycle through your message history. Click the Gear icon to customize chat. <LINE> <LINE> Happy surviving!

# Adicione nomes de usu�rio desconhecidos � lista de permiss�es quando os jogadores entrarem. Os jogadores fornecer�o seu pr�prio nome de usu�rio/senha ao ingressar. (Isto � para servidores Open=true)
AutoCreateUserInWhiteList=false

# Exibe nomes de usu�rio acima da cabe�a do jogador no jogo.
DisplayUserName=true

# Exibe o nome e sobrenome acima da cabe�a do jogador.
ShowFirstAndLastName=false

# For�a cada novo jogador a aparecer nas coordenadas de mapa X,Y,Z. Encontre as coordenadas desejadas em map.projectzomboid.com. (Ignorado quando 0,0,0)
SpawnPoint=0,0,0

# Os jogadores podem entrar e sair do PVP individualmente. Um jogador s� pode machucar outro, quando pelo menos um deles estiver no modo PVP - representado pela caveira � esquerda da tela. Quando SafetySystem=false, os jogadores podem se machucar a qualquer momento se o PVP estiver ativado.
SafetySystem=true

# Exibe um �cone de caveira sobre a cabe�a dos jogadores que entraram no modo PVP
ShowSafety=true

# O tempo que leva para um jogador entrar e sair do modo PVP\nM�nimo = 0 M�ximo = 1000 Padr�o = 2
SafetyToggleTimer=2

# O atraso antes que um jogador possa entrar ou sair do modo PVP novamente, tendo feito isso recentemente\nM�nimo = 0 M�ximo = 1000 Padr�o = 3
SafetyCooldownTimer=3

# Tipos de itens com os quais novos jogadores aparecem.\nSepare v�rios tipos de itens com v�rgulas.\nExemplo: Base.Axe,Base.Bag_BigHikingBag
SpawnItems=

# Porta inicial padr�o para dados do jogador. Se for UDP, esta � uma das duas portas usadas.\nM�nimo = 0 M�ximo = 65535 Padr�o = 16261
DefaultPort=16261

# M�nimo = 0 M�ximo = 65535 Padr�o = 16262
UDPPort=16262

# ResetID determina se o servidor passou por uma reinicializa��o por software. Se este n�mero corresponder ao jogador, o jogador deve criar um novo personagem. Usado em conjunto com PlayerServerID. � altamente recomend�vel que voc� fa�a backup desses IDs em algum lugar\nM�nimo = 0 M�ximo = 2147483647 Padr�o = 259144050
ResetID=259144050

# Digite o ID de carregamento do mod aqui. Ele pode ser encontrado em \Steam\steamapps\workshop\modID\mods\modName\info.txt
Mods=

# Digite o nome da pasta do mod encontrado em \Steam\steamapps\workshop\modID\mods\modName\media\maps\
Map=Muldraugh, KY

# Expulsa jogadores em que os arquivos do jogo n�o correspondem com os do servidor
DoLuaChecksum=true

DenyLoginOnOverloadedServer=true

# Mostra o servidor no navegador do jogo. (Nota: os servidores habilitados para Steam est�o sempre vis�veis no navegador do servidor Steam)
Public=false

# Nome do servidor exibido no navegador do jogo e, se aplic�vel, no navegador Steam
PublicName=My PZ Server

# Descri��o exibida no navegador do servidor p�blico do jogo. Digitar \n criar� uma nova linha na sua descri��o
PublicDescription=

# N�mero m�ximo de jogadores que podem estar no servidor ao mesmo tempo. Isso exclui os administradores.
# AVISO: a contagem de jogadores do servidor acima de 32 resultar� potencialmente, de forma negativa, no fluxo e dessincroniza��o de mapas. Por favor, avance com cuidado.\nM�nimo = 1 M�ximo = 100 Padr�o = 32
MaxPlayers=32

# Limite de ping, em milissegundos, antes que um jogador seja expulso do servidor. (Definir como 100 para desabilitar)\nM�nimo = 100 M�ximo = 2147483647 Padr�o = 400
PingLimit=400

# Ap�s X horas, todos os recipientes do mundo ir�o reaparecer. Para gerar loot, um recipiente deve ter sido looteado pelo menos uma vez. O reaparecimento de loot n�o � afetado pela visibilidade ou loots subsequentes.\nM�nimo = 0 M�ximo = 2147483647 Padr�o = 0
HoursForLootRespawn=0

# Recipientes com um n�mero de itens maior ou igual a essa configura��o n�o reaparecer�o\nM�nimo = 1 M�ximo = 2147483647 Padr�o = 4
MaxItemsForLootRespawn=4

# Itens n�o reaparecer�o em constru��es que os jogadores tenham barricado ou constru�do
ConstructionPreventsLootRespawn=true

# Remove as contas de jogadores da lista de permiss�es ap�s a morte. Isso impede que os jogadores criem um novo personagem ap�s a morte em servidores Open=false
DropOffWhiteListAfterDeath=false

# Todas as formas de fogo s�o desativadas - exceto fogueiras
NoFire=false

# Se marcado, toda vez que um jogador morrer, uma mensagem global ser� exibida no chat
AnnounceDeath=false

# N�mero de minutos no jogo que leva para ler uma p�gina de um livro\nM�nimo = 0,00 M�ximo = 60,00 Padr�o = 1,00
MinutesPerPage=1.0

# As partes carregadas do mapa s�o salvas ap�s esse n�mero definido de minutos do mundo real. (O mapa geralmente � salvo somente depois que os jogadores saem de uma �rea carregada)\nM�nimo = 0 M�ximo = 2147483647 Padr�o = 0
SaveWorldEveryMinutes=0

# Tanto administradores quanto jogadores podem reivindicar bases
PlayerSafehouse=false

# Apenas administradores podem reivindicar bases
AdminSafehouse=false

# Permite que n�o membros entrem em uma base sem serem convidados
SafehouseAllowTrepass=true

# Permite que o fogo danifique bases
SafehouseAllowFire=true

# Permite que n�o membros peguem itens de bases
SafehouseAllowLoot=true

# Os jogadores v�o reaparecer em uma base do qual eram membros antes de morrer
SafehouseAllowRespawn=false

# Os jogadores devem ter sobrevivido a esse n�mero de dias no jogo antes de poderem reivindicar uma base\nM�nimo = 0 M�ximo = 2147483647 Padr�o = 0
SafehouseDaySurvivedToClaim=0

# Os jogadores s�o removidos automaticamente de uma base que n�o visitaram por tantas horas do mundo real\nM�nimo = 0 M�ximo = 2147483647 Padr�o = 144
SafeHouseRemovalTime=144

# Controla se os jogadores podem reivindicar edif�cios n�o residenciais.
SafehouseAllowNonResidential=false

# Permite que os jogadores destruam objetos do mundo com marretas
AllowDestructionBySledgehammer=true

# Permite que os jogadores destruam objetos do mundo apenas em sua base (exigir que AllowDestructionBySledgehammer seja verdadeiro).
SledgehammerOnlyInSafehouse=false

# Expulsa jogadores que parecem estar se movendo mais r�pido do que � poss�vel. Pode ser bug - use com cuidado.
KickFastPlayers=false

# ServerPlayerID determina se um personagem � de outro servidor ou single player. Este valor pode ser alterado por soft resets. Se este n�mero corresponder ao jogador, o jogador deve criar um novo personagem. Isso � usado em conjunto com ResetID. � altamente recomend�vel que voc� fa�a backup desses IDs em algum lugar
ServerPlayerID=1281471003

# A porta para o RCON (Console Remoto)\nM�nimo = 0 M�ximo = 65535 Padr�o = 27015
RCONPort=27015

# Senha RCON (Escolha uma senha forte)
RCONPassword=

# Permite a integra��o global de bate-papo por texto com um canal Discord
DiscordEnable=false

# Token de acesso do bot do Discord
DiscordToken=

# O nome do canal Discord. (Tente a op��o de ID de canal separado se tiver problemas)
DiscordChannel=

# O ID do canal Discord. (Use se tiver problemas com a op��o de nome do canal Discord)
DiscordChannelID=

# Os jogadores devem saber essa senha para ingressar no servidor. (Ignorado ao hospedar um servidor atrav�s do bot�o Host)
Password=

# Limita o n�mero de contas diferentes que um �nico usu�rio Steam pode criar neste servidor. Ignorado ao usar o bot�o Hosts.\nM�nimo = 0 M�ximo = 2147483647 Padr�o = 0
MaxAccountsPerUser=0

# Allow co-op/splitscreen players
AllowCoop=true

# Os jogadores podem dormir quando seu sobrevivente fica cansado, mas eles N�O PRECISAM dormir
SleepAllowed=false

# Os jogadores se cansam e precisam dormir. (Ignorado se SleepAllowed=false)
SleepNeeded=false

KnockedDownAllowed=true

SneakModeHideFromOtherPlayers=true

# Liste os IDs de Mods do Workshop para o servidor baixar. Cada um deve ser separado por um ponto e v�rgula. Exemplo: WorkshopItems=514427485;513111049
WorkshopItems=

# Mostrar nomes de usu�rio e avatares do Steam na lista de jogadores. Pode ser verdadeiro (vis�vel para todos), falso (vis�vel para ningu�m) ou admin (vis�vel apenas para administradores)
SteamScoreboard=true

# Ative o sistema Steam VAC
SteamVAC=true

# Tente configurar um gateway de internet habilitado para UPnP para configurar automaticamente as regras de encaminhamento de porta. O servidor retornar� �s portas padr�o se isso falhar
UPnP=true

# VOIP � ativado quando marcado
VoiceEnable=true

# A dist�ncia m�nima do bloco em que os sons do VOIP podem ser ouvidos. O padr�o � 10\nM�nimo = 0,00 M�ximo = 100000,00 Padr�o = 10,00
VoiceMinDistance=10.0

# A dist�ncia m�xima do bloco em que os sons do VOIP podem ser ouvidos. O padr�o � 300\nM�nimo = 0,00 M�ximo = 100000,00 Padr�o = 100,00
VoiceMaxDistance=100.0

# Ativar �udio direcional para VOIP
Voice3D=true

# M�nimo = 10,00 M�ximo = 150,00 Padr�o = 70,00
SpeedLimit=70.0

LoginQueueEnabled=false

# Mínimo = 20 Máximo = 1200 Padrão = 60
LoginQueueConnectTimeout=120

# Defina o IP do qual o servidor � transmitido. Isso � para configura��es de rede com v�rios endere�os IP, como grupos de servidores
server_browser_announced_ip=

# Os jogadores podem renascer no jogo nas coordenadas onde morreram
PlayerRespawnWithSelf=false

# Os jogadores podem renascer no jogo em uma tela dividida / localiza��o do jogador do Remote Play
PlayerRespawnWithOther=false

# Controla a rapidez com que o tempo passa enquanto os jogadores dormem. Esse valor multiplica a velocidade do tempo que passa durante o sono.\nM�nimo = 1,00 M�ximo = 100,00 Padr�o = 40,00
FastForwardMultiplier=40.0

# A base age como uma casa normal se um membro dela estiver conectado (t�o seguro quando os jogadores est�o offline)
DisableSafehouseWhenPlayerConnected=false

# Os jogadores podem criar fac��es quando verdadeiro
Faction=true

# Os jogadores devem sobreviver a esse n�mero de dias no jogo antes de serem autorizados a criar uma fac��o\nM�nimo = 0 M�ximo = 2147483647 Padr�o = 0
FactionDaySurvivedToCreate=0

# N�mero de jogadores necess�rios como membros da fac��o antes que o propriet�rio da fac��o possa criar uma tag de grupo\nM�nimo = 1 M�ximo = 2147483647 Padr�o = 1
FactionPlayersRequiredForTag=1

# Desativa as transmiss�es de r�dio de jogadores com n�vel de acesso
DisableRadioStaff=false

# Desativa as transmiss�es de r�dio de jogadores com n�vel de acesso 'admin'
DisableRadioAdmin=true

# Desativa as transmiss�es de r�dio de jogadores com n�vel de acesso 'gm'
DisableRadioGM=true

# Desativa as transmiss�es de r�dio de jogadores com n�vel de acesso 'supervisor'
DisableRadioOverseer=false

# Desativa as transmiss�es de r�dio de jogadores com n�vel de acesso 'moderador'
DisableRadioModerator=false

# Desativa as transmiss�es de r�dio de jogadores invis�veis
DisableRadioInvisible=true

# Lista de comandos separados por ponto e v�rgula que n�o ser�o gravados no log do servidor cmd.txt. Por exemplo: \n-ve�culo. Inserir * significa N�O escrever nenhum comando de ve�culo. Inserindo: \n+vehicle.installPart significa que ESCREVA esse comando
ClientCommandFilter=-vehicle.*;+vehicle.damageWindow;+vehicle.fixPart;+vehicle.installPart;+vehicle.uninstallPart

# Lista de a��es separadas por ponto e v�rgula que ser�o gravadas no log do servidor ClientActionLogs.txt
ClientActionLogs=ISEnterVehicle;ISExitVehicle;ISTakeEngineParts;

# Acompanha as altera��es nos n�veis de vantagens do jogador no log do servidor PerkLog.txt
PerkLogs=true

# N�mero m�ximo de itens que podem ser colocados em um recipiente. Zero significa que n�o h� limite. (OBSERVA��O: Isso inclui itens pequenos individuais, como pregos. Um limite de 50 significa que apenas 50 pregos podem ser armazenados.)\nM�nimo = 0 M�ximo = 9000 Padr�o = 0
ItemNumbersLimitPerContainer=0

# N�mero de dias antes que os respingos de sangue antigos sejam removidos.
# A remo��o acontece quando partes do mapa s�o carregados.
# Zero significa que eles nunca desaparecer�o\nM�nimo = 0 M�ximo = 365 Padr�o = 0
BloodSplatLifespanDays=0

# Permite o uso de caracteres n�o ASCII (cir�lico etc) em nomes de usu�rio
AllowNonAsciiUsername=false

BanKickGlobalSound=true

# Se ativado, quando o HoursForCorpseRemoval for acionado, ele tamb�m remover� os cad�veres do jogador do ch�o
RemovePlayerCorpsesOnCorpseRemoval=false

# Se verdadeiro, o jogador pode usar o bot�o "excluir tudo" nas caixas
TrashDeleteAll=false

# Se verdadeiro, o jogador pode bater novamente quando atingido por outro jogador
PVPMeleeWhileHitReaction=false

# Se verdadeiro, os jogadores ter�o que passar o mouse sobre algu�m para ver seu nome de exibi��o
MouseOverToSeeDisplayName=true

# Se verdadeiro, omite automaticamente o jogador que voc� n�o pode ver (como zumbis)
HidePlayersBehindYou=true

# Adiciona dano para ataques corpo a corpo PVP\nM�nimo = 0,00 M�ximo = 500,00 Padr�o = 30,00
PVPMeleeDamageModifier=30.0

# Adiciona dano para ataques � dist�ncia PVP\nM�nimo = 0,00 M�ximo = 500,00 Padr�o = 50,00
PVPFirearmDamageModifier=50.0

# Modifica o alcance da atra��o de zumbis para carros (valores mais baixos podem ajudar com lags)\nM�nimo = 0,00 M�ximo = 10,00 Padr�o = 0,50
CarEngineAttractionModifier=0.5

# Controla se os jogadores esbarram (e derrubam) outros jogadores ao passar por eles.
PlayerBumpPlayer=false

# Controla a exibi��o de jogadores remotos no mapa do jogo.\n1 = Oculto 2 = Amigos 3 = Todos\nM�nimo = 1 M�ximo = 3 Padr�o = 1
MapRemotePlayerVisibility=1

# M�nimo = 1 M�ximo = 300 Padr�o = 5
BackupsCount=5

BackupsOnStart=true

BackupsOnVersionChange=true

# M�nimo = 0 M�ximo = 1500 Padr�o = 0
BackupsPeriod=0

# Desativa a prote��o do anti-cheat para o tipo 1.
AntiCheatProtectionType1=true

# Desativa a prote��o do anti-cheat para o tipo 2.
AntiCheatProtectionType2=true

# Desativa a prote��o do anti-cheat para o tipo 3.
AntiCheatProtectionType3=true

# Desativa a prote��o do anti-cheat para o tipo 4.
AntiCheatProtectionType4=true

# Desativa a prote��o do anti-cheat para o tipo 5.
AntiCheatProtectionType5=true

# Desativa a prote��o do anti-cheat para o tipo 6.
AntiCheatProtectionType6=true

# Desativa a prote��o do anti-cheat para o tipo 7.
AntiCheatProtectionType7=true

# Desativa a prote��o do anti-cheat para o tipo 8.
AntiCheatProtectionType8=true

# Desativa a prote��o do anti-cheat para o tipo 9.
AntiCheatProtectionType9=true

# Desativa a prote��o do anti-cheat para o tipo 10.
AntiCheatProtectionType10=true

# Desativa a prote��o do anti-cheat para o tipo 11.
AntiCheatProtectionType11=true

# Desativa a prote��o do anti-cheat para o tipo 12.
AntiCheatProtectionType12=true

# Desativa a prote��o do anti-cheat para o tipo 13.
AntiCheatProtectionType13=true

# Desativa a prote��o do anti-cheat para o tipo 14.
AntiCheatProtectionType14=true

# Desativa a prote��o do anti-cheat para o tipo 15.
AntiCheatProtectionType15=true

# Desativa a prote��o do anti-cheat para o tipo 16.
AntiCheatProtectionType16=true

# Desativa a prote��o do anti-cheat para o tipo 17.
AntiCheatProtectionType17=true

# Desativa a prote��o do anti-cheat para o tipo 18.
AntiCheatProtectionType18=true

# Desativa a prote��o do anti-cheat para o tipo 19.
AntiCheatProtectionType19=true

# Desativa a prote��o do anti-cheat para o tipo 20.
AntiCheatProtectionType20=true

AntiCheatProtectionType21=true

AntiCheatProtectionType22=true

AntiCheatProtectionType23=true

AntiCheatProtectionType24=true

# Multiplicador de valor limite para prote��o do anti-cheat: tipo 2.\nM�nimo = 1,00 M�ximo = 10,00 Padr�o = 3,00
AntiCheatProtectionType2ThresholdMultiplier=3.0

# Multiplicador de valor limite para prote��o do anti-cheat: tipo 3.\nM�nimo = 1,00 M�ximo = 10,00 Padr�o = 1,00
AntiCheatProtectionType3ThresholdMultiplier=1.0

# Multiplicador de valor limite para prote��o do anti-cheat: tipo 4.\nM�nimo = 1,00 M�ximo = 10,00 Padr�o = 1,00
AntiCheatProtectionType4ThresholdMultiplier=1.0

# Multiplicador de valor limite para prote��o do anti-cheat: tipo 9.\nM�nimo = 1,00 M�ximo = 10,00 Padr�o = 1,00
AntiCheatProtectionType9ThresholdMultiplier=1.0

# Multiplicador de valor limite para prote��o do anti-cheat: tipo 15.\nM�nimo = 1,00 M�ximo = 10,00 Padr�o = 1,00
AntiCheatProtectionType15ThresholdMultiplier=1.0

# Multiplicador de valor limite para prote��o do anti-cheat: tipo 20.\nM�nimo = 1,00 M�ximo = 10,00 Padr�o = 1,00
AntiCheatProtectionType20ThresholdMultiplier=1.0

# M�nimo = 1,00 M�ximo = 10,00 Padr�o = 1,00
AntiCheatProtectionType22ThresholdMultiplier=1.0

# M�nimo = 1,00 M�ximo = 10,00 Padr�o = 6,00
AntiCheatProtectionType24ThresholdMultiplier=6.0